import React, { createContext, useContext, useState } from 'react';

export type AppLanguage = 'en' | 'hi' | 'od' | 'te';

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
}

const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.explore': 'Explore Map',
    'nav.report': 'Raise a Complaint',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',

    // Landing page
    'landing.activeTarget': 'Active Target',
    'landing.hero1': 'Priority Based',
    'landing.hero2': 'Constituency Planning.',
    'landing.subtitle': 'People\'s Priorities™ makes your voice heard. We turn real citizen voice notes, photos, and reports into verified community priorities so decision-makers can solve public issues faster.',
    'landing.cta.explore': 'Launch Interactive Map',
    'landing.cta.report': 'Raise a Complaint',
    'landing.howitworks': 'How People\'s Priorities™ Works',
    'landing.howitworks.desc': 'A simple, transparent bridge connecting everyday citizens directly to decision-makers. You report the real issues around you—our smart system verifies, groups, and ranks them by actual public need.',
    'landing.step1.title': '1. Easy Citizen Reporting',
    'landing.step1.desc': 'Speak naturally into your phone in Hindi, Odia, Telugu, or English, take a quick photo of a broken road or water pipe, or type a note. Our smart system listens and verifies your real report instantly.',
    'landing.step1.badge': 'Spoken Voice & Photo Verified',
    'landing.step2.title': '2. Grouping & Urgency Ranking',
    'landing.step2.desc': 'When multiple neighbors report the same broken road or drainage issue, we automatically group those reports into one major hotspot and rank its priority based on actual community need and affected population.',
    'landing.step2.badge': 'Fair & Transparent Priority',
    'landing.step3.title': '3. Action for Leaders & MPs',
    'landing.step3.desc': 'Village leaders and MPs get a clean, ranked checklist of what needs fixing first—complete with verified photos, citizen voice notes, and estimated budget requirements so funds go directly where people need them most.',
    'landing.step3.badge': 'Direct Public Impact',
    'landing.footer.title': 'Ready to Explore',
    'landing.footer.desc': 'Experience the 65% cartographic viewport, deep evidence tabs, and real-time civic intelligence.',
    'landing.footer.btn1': 'Open Map Viewport →',
    'landing.footer.btn2': 'Open MP Decision Matrix',
    'landing.heroRadar': 'HERO RADAR',
    'landing.clusters': 'Clusters',
    'landing.pinsActive': 'Pins Active',
    'landing.score': 'Score:',
    'landing.reports': 'Reports',
    'landing.individualPin': '🟣 Individual Pin',
    'landing.monitoredDemand': 'Monitored Demand',
    'landing.noClusters': 'No active clusters in',
    'landing.noClustersDesc': 'The real-time GIS spatial canvas is live. Submit a verified citizen report to initiate DBSCAN clustering!',
    'landing.deepAnalysis': 'Deep Analysis →',

    // Report page
    'report.title': 'Raise a complaint here',
    'report.canvas': 'Active Canvas',
    'report.viewmap': 'View Live Map Viewport',
    'report.viewmap.mobile': 'View Live Map',
    'report.gps': 'GPS Lock',
    'report.gps.verified': '✓ Verified',
    'report.gps.acquiring': 'Acquiring…',
    'report.gps.denied': 'Location Access Denied',
    'report.gps.retry': 'Retry',
    'report.gps.manual': 'Manual Entry',
    'report.gps.block': 'Block',
    'report.gps.dist': 'Dist',
    'report.gps.relock': 'Relock GPS Coordinates',
    'report.category': 'Select Issue Category',
    'report.method': 'Choose Report Method',
    'report.method.desc': 'Supports voice memos, smartphone photos, and text',
    'report.tab.text': 'Write Complaint',
    'report.tab.photo': 'Photo Proof',
    'report.tab.voice': 'Voice Report',
    'report.voice.lang': 'Language:',
    'report.voice.rec': 'Recording… Speak Clearly',
    'report.voice.recorded': 'Voice Note Recorded ✓',
    'report.voice.click': 'Click Mic to Record',
    'report.voice.stop': 'Stop & Transcribe',
    'report.voice.play': 'Play',
    'report.voice.playing': 'Playing…',
    'report.voice.speak': 'Speak Loud & Clear into your mic',
    'report.photo.click': 'Click Photo of Issue with Camera',
    'report.photo.or': 'Or upload existing image (JPG, PNG, WEBP)',
    'report.photo.btn': '📷 Open Camera / Select File',
    'report.photo.retake': 'Retake Photo',
    'report.text.label': 'Detailed Description',
    'report.text.placeholder': 'Write your problem here…',
    'report.submit.text': '📝 Submit Complaint & Publish to Live Map',
    'report.submit.photo': '📷 Submit Photo Proof & Publish to Live Map',
    'report.submit.voice': '🎤 Submit Voice Report & Publish to Live Map',
    'report.submit.loading': 'Auditing & Publishing to Live Map…',

    // Explore page
    'explore.title': 'Live Complaint & AI Cluster Priority Map',
    'explore.switchReport': 'Raise a Complaint',
    'explore.all': 'All Categories',
    'explore.searchPlaceholder': 'Search locations or descriptions...',
    'explore.filterTitle': 'Filter by Category',
    'explore.canvas': 'ACTIVE CANVAS',
    'explore.spatialLedger': 'Demand Cluster List',
    'explore.synced': 'Synced with Dashboard • 100% Canonical Data',
    'explore.clusters': 'Clusters',
    'explore.complaints': 'Complaints',
    'explore.searchPlaceholderClusters': 'Search cluster, block, category...',
    'explore.searchPlaceholderReports': 'Search complaint text, voice quote, issue...',
    'explore.layer.infra': 'Public Infra',
    'explore.layer.citizen': 'Citizen Inputs',
    'explore.layer.demographics': 'Demographics',
    'explore.layer.streets': '🗺️ Streets',
    'explore.layer.satellite': '🛰️ Satellite',
    'explore.tab1': '1. AI Overview',
    'explore.tab2': '2. 8-Factor Formula',
    'explore.tab3': '3. Citizen Voices',
    'explore.tab4': '4. Census & Demographics',
    'explore.tab5': '5. Fraud Defense',
    'explore.tab6': '6. What-If Simulator',
    'explore.tab7': '7. Before/After Audit',
    'explore.drawer.confidence': 'High-Confidence Cluster Verified',
    'explore.drawer.recAction': 'Recommended Action',
    'explore.drawer.mandate': 'Issue Fast-Track Mandate',
    'explore.drawer.aiHeadline': 'AI Executive Headline',
    'explore.drawer.reasoning': 'Geospatial & Citizen Reasoning',
    'explore.drawer.verifiedReports': 'Verified Citizen Reports',
    'explore.drawer.impactedCitizens': 'Impacted Citizens',
    'explore.drawer.censusSync': 'Census 2021/2026 Sync',
    'explore.drawer.severityRating': 'Infra Severity Rating',

    // Dashboard page
    'dashboard.title': 'Live Priority Dashboard',
    'dashboard.switchmap': 'Switch to GIS Map',
    'dashboard.role.title': 'Active Viewport Lens (Role-Based Access Control):',
    'dashboard.role.mp': 'MP (Member of Parliament)',
    'dashboard.role.collector': 'District Collector / MLA',
    'dashboard.role.panchayat': 'Panchayat Secretary',
    'dashboard.weights.title': '8-Factor Weight Calibration',
    'dashboard.weights.reset': 'Reset',
    'dashboard.weights.desc': 'Adjust formula multipliers to see how citizen demand volume vs. infrastructure gaps shift rank order.',
    'dashboard.weights.demand': 'Citizen Demand Velocity Weight (D)',
    'dashboard.weights.demographic': 'Demographic Needs Weight (P)',
    'dashboard.weights.infra': 'Infrastructure Deficit Weight (U)',
    'dashboard.weights.urgency': 'Urgency & Safety Weight (G)',
    'dashboard.roleDesc': 'All actions in this view are read-only or scoped to field verification checklists and citizen feedback voting.',
    'dashboard.returnToMp': 'Return to MP Demand Priority Engine',
    'dashboard.viewportActiveFor': 'Viewport Mode active for:',

    // Admin page
    'admin.title': 'Dataset Health & Backend Recalibration Engine',
    'admin.pipelineStatus': 'PIPELINE STATUS',
    'admin.onlineSync': '🟢 5 Datasets Online & Synchronized',
    'admin.backToDashboard': 'Back to MP Dashboard',
    'admin.systemLogs': 'System Logs & Pipeline Output',
    'admin.dbscanTitle': 'DBSCAN & Multi-Factor Recalibration',
    'admin.verifiedDatasets': 'Verified Government & Municipal Datasets',
    'admin.snapshotRollback': 'Spatial Snapshot Rollback',
    'admin.uploadBtn': 'Upload New GIS Vector or Census GeoJSON File to Pipeline',
    'admin.triggerBtn': 'Trigger Full Backend Recalibration Now',

    // Categories
    'cat.all': 'All Categories',
    'cat.road': 'Roads & Bridges',
    'cat.drainage': 'Urban Drainage',
    'cat.healthcare': 'Healthcare',
    'cat.water': 'Drinking Water',
    'cat.schools': 'Schools & Edu',
    'cat.electricity': 'Electricity',
    'cat.all_clusters': 'All Clusters',
    'cat.all_complaints': 'All Complaints',
  },
  hi: {
    // Navbar
    'nav.home': 'होम',
    'nav.explore': 'मानचित्र देखें',
    'nav.report': 'शिकायत दर्ज करें',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.admin': 'व्यवस्थापक',

    // Landing page
    'landing.activeTarget': 'सक्रिय क्षेत्र',
    'landing.hero1': 'प्राथमिकता आधारित',
    'landing.hero2': 'निर्वाचन क्षेत्र योजना।',
    'landing.subtitle': 'People\'s Priorities™ आपकी आवाज़ को निर्णयकर्ताओं तक पहुँचाता है। हम नागरिकों के वॉइस नोट्स, फ़ोटो और रिपोर्ट को सत्यापित प्राथमिकताओं में बदलते हैं ताकि स्थानीय समस्याओं का समाधान तेज़ी से हो सके।',
    'landing.cta.explore': 'लाइव मानचित्र लॉन्च करें',
    'landing.cta.report': 'शिकायत दर्ज करें',
    'landing.howitworks': 'People\'s Priorities™ कैसे काम करता है',
    'landing.howitworks.desc': 'आम नागरिकों को सीधे निर्णयकर्ताओं से जोड़ने वाला एक सरल और पारदर्शी मंच। आप अपनी भाषा में स्थानीय समस्याओं की रिपोर्ट करते हैं—हमारा सिस्टम उन्हें सत्यापित करता है और प्राथमिकता के आधार पर व्यवस्थित करता है।',
    'landing.step1.title': '1. आसान नागरिक रिपोर्टिंग',
    'landing.step1.desc': 'अपने फ़ोन में हिंदी, उड़िया, तेलुगु या अंग्रेज़ी में सहजता से बोलें, टूटी सड़क या पानी की पाइपलाइन की फ़ोटो लें, या लिखकर बताएं। हमारा स्मार्ट सिस्टम आपकी रिपोर्ट को तुरंत सुनता और सत्यापित करता है।',
    'landing.step1.badge': 'वॉयस और फ़ोटो सत्यापित',
    'landing.step2.title': '2. स्मार्ट समूहीकरण व रैंकिंग',
    'landing.step2.desc': 'जब कई पड़ोसी एक ही समस्या की रिपोर्ट करते हैं, तो हम स्वचालित रूप से उन सभी रिपोर्टों को एक प्रमुख हॉटस्पॉट में जोड़ते हैं और प्रभावित आबादी व आवश्यकता के आधार पर उसकी प्राथमिकता तय करते हैं।',
    'landing.step2.badge': 'निष्पक्ष और पारदर्शी प्राथमिकता',
    'landing.step3.title': '3. नेताओं और सांसदों के लिए कार्रवाई',
    'landing.step3.desc': 'जनप्रतिनिधियों और सांसदों को सबसे ज़रूरी कार्यों की एक स्पष्ट सूची मिलती है—जिसमें सत्यापित फ़ोटो, नागरिकों के वॉइस नोट्स और अनुमानित बजट शामिल होता है ताकि फंड सही जगह लग सके।',
    'landing.step3.badge': 'सीधा जनहित प्रभाव',
    'landing.footer.title': 'खोजने के लिए तैयार',
    'landing.footer.desc': '65% कार्टोग्राफिक व्यूपोर्ट, गहन साक्ष्य टैब और वास्तविक समय नागरिक खुफिया जानकारी का अनुभव करें।',
    'landing.footer.btn1': 'मानचित्र व्यूपोर्ट खोलें →',
    'landing.footer.btn2': 'एमपी निर्णय मैट्रिक्स खोलें',
    'landing.heroRadar': 'हीरो रडार',
    'landing.clusters': 'क्लस्टर',
    'landing.pinsActive': 'सक्रिय पिन',
    'landing.score': 'स्कोर:',
    'landing.reports': 'रिपोर्ट',
    'landing.individualPin': '🟣 व्यक्तिगत पिन',
    'landing.monitoredDemand': 'निगरानी की गई मांग',
    'landing.noClusters': 'अभी तक कोई सक्रिय क्लस्टर नहीं है',
    'landing.noClustersDesc': 'वास्तविक समय जीआईएस स्थानिक कैनवास लाइव है। डीबीएससीएएन क्लस्टरिंग शुरू करने के लिए एक सत्यापित नागरिक रिपोर्ट सबमिट करें!',
    'landing.deepAnalysis': 'गहन विश्लेषण →',

    // Report page
    'report.title': 'शिकायत यहाँ दर्ज करें',
    'report.canvas': 'सक्रिय कैनवास',
    'report.viewmap': 'लाइव मानचित्र दृश्यपोर्ट देखें',
    'report.viewmap.mobile': 'लाइव मानचित्र देखें',
    'report.gps': 'GPS लॉक',
    'report.gps.verified': '✓ सत्यापित',
    'report.gps.acquiring': 'खोज की जा रही है…',
    'report.gps.denied': 'स्थान पहुंच अस्वीकृत',
    'report.gps.retry': 'पुनः प्रयास करें',
    'report.gps.manual': 'मैनुअल प्रविष्टि',
    'report.gps.block': 'ब्लॉक',
    'report.gps.dist': 'जिला',
    'report.gps.relock': 'GPS निर्देशांक पुनः लॉक करें',
    'report.category': 'समस्या श्रेणी चुनें',
    'report.method': 'रिपोर्ट विधि चुनें',
    'report.method.desc': 'वॉइस मेमो, स्मार्टफ़ोन फ़ोटो और लिखित टेक्स्ट का समर्थन करता',
    'report.tab.text': 'शिकायत लिखें',
    'report.tab.photo': 'फोटो प्रमाण',
    'report.tab.voice': 'आवाज रिपोर्ट',
    'report.voice.lang': 'भाषा:',
    'report.voice.rec': 'रिकॉर्डिंग जारी है… स्पष्ट बोलें',
    'report.voice.recorded': 'वॉइस नोट रिकॉर्ड किया गया ✓',
    'report.voice.click': 'रिकॉर्ड करने के लिए माइक दबाएं',
    'report.voice.stop': 'रोकें और ट्रांसक्राइब करें',
    'report.voice.play': 'चलाएं',
    'report.voice.playing': 'चल रहा है…',
    'report.voice.speak': 'जोर से और स्पष्ट बोलें',
    'report.photo.click': 'कैमरे से समस्या की तस्वीर लें',
    'report.photo.or': 'या मौजूदा छवि अपलोड करें (JPG, PNG, WEBP)',
    'report.photo.btn': '📷 कैमरा खोलें / फ़ाइल चुनें',
    'report.photo.retake': 'पुनः तस्वीर लें',
    'report.text.label': 'विस्तृत विवरण',
    'report.text.placeholder': 'अपनी समस्या यहाँ लिखें…',
    'report.submit.text': '📝 शिकायत जमा करें और लाइव मानचित्र पर प्रकाशित करें',
    'report.submit.photo': '📷 फोटो प्रमाण जमा करें और लाइव मानचित्र पर प्रकाशित करें',
    'report.submit.voice': '🎤 आवाज रिपोर्ट जमा करें और लाइव मानचित्र पर प्रकाशित करें',
    'report.submit.loading': 'ऑडिटिंग और प्रकाशन जारी है…',

    // Explore page
    'explore.title': 'लाइव शिकायत एवं एआई क्लस्टर प्राथमिकता मानचित्र',
    'explore.switchReport': 'शिकायत दर्ज करें',
    'explore.all': 'सभी श्रेणियां',
    'explore.searchPlaceholder': 'स्थानों या विवरणों की खोज करें...',
    'explore.filterTitle': 'श्रेणी अनुसार छानें',
    'explore.canvas': 'सक्रिय कैनवास',
    'explore.spatialLedger': 'स्थानिक मांग बही',
    'explore.synced': 'डैशबोर्ड के साथ समन्वयित • 100% प्रामाणिक डेटा',
    'explore.clusters': 'क्लस्टर',
    'explore.complaints': 'शिकायतें',
    'explore.searchPlaceholderClusters': 'क्लस्टर, ब्लॉक, श्रेणी खोजें...',
    'explore.searchPlaceholderReports': 'शिकायत पाठ, आवाज प्रतिलेख, समस्या खोजें...',
    'explore.layer.infra': 'सार्वजनिक बुनियादी ढांचा',
    'explore.layer.citizen': 'नागरिक इनपुट',
    'explore.layer.demographics': 'जनसांख्यिकी',
    'explore.layer.streets': '🗺️ सड़कें',
    'explore.layer.satellite': '🛰️ उपग्रह',
    'explore.tab1': '1. एआई अवलोकन',
    'explore.tab2': '2. 8-कारक सूत्र',
    'explore.tab3': '3. नागरिक आवाजें',
    'explore.tab4': '4. जनगणना और जनसांख्यिकी',
    'explore.tab5': '5. धोखाधड़ी रक्षा',
    'explore.tab6': '6. व्हाट-इफ सिम्युलेटर',
    'explore.tab7': '7. ऑडिट से पहले/बाद',
    'explore.drawer.confidence': 'उच्च-विश्वास क्लस्टर सत्यापित',
    'explore.drawer.recAction': 'अनुशंसित कार्रवाई',
    'explore.drawer.mandate': 'फास्ट-ट्रैक जनादेश जारी करें',
    'explore.drawer.aiHeadline': 'एआई कार्यकारी हेडलाइन',
    'explore.drawer.reasoning': 'भू-स्थानिक और नागरिक तर्क',
    'explore.drawer.verifiedReports': 'सत्यापित नागरिक रिपोर्ट',
    'explore.drawer.impactedCitizens': 'प्रभावित नागरिक',
    'explore.drawer.censusSync': 'जनगणना 2021/2026 समन्वयन',
    'explore.drawer.severityRating': 'बुनियादी ढांचा गंभीरता रेटिंग',

    // Dashboard page
    'dashboard.title': 'लाइव प्राथमिकता डैशबोर्ड',
    'dashboard.switchmap': 'जीआईएस मानचित्र पर जाएं',
    'dashboard.role.title': 'सक्रिय दृश्य क्षेत्र लेंस (भूमिका-आधारित पहुंच नियंत्रण):',
    'dashboard.role.mp': 'सांसद (संसद सदस्य)',
    'dashboard.role.collector': 'जिला कलेक्टर / विधायक',
    'dashboard.role.panchayat': 'पंचायत सचिव',
    'dashboard.weights.title': '8-कारक वजन अंशांकन',
    'dashboard.weights.reset': 'रीसेट',
    'dashboard.weights.desc': 'नागरिक मांग की मात्रा बनाम बुनियादी ढांचे के अंतर को देखने के लिए सूत्र गुणक को समायोजित करें।',
    'dashboard.weights.demand': 'नागरिक मांग वेग भार (D)',
    'dashboard.weights.demographic': 'जनसांख्यिकीय आवश्यकता भार (P)',
    'dashboard.weights.infra': 'बुनियादी ढांचा घाटा भार (U)',
    'dashboard.weights.urgency': 'तत्कालिकता और सुरक्षा भार (G)',
    'dashboard.roleDesc': 'इस दृश्य में सभी क्रियाएं केवल पढ़ने के लिए हैं या फ़ील्ड सत्यापन चेकलिस्ट और नागरिक प्रतिक्रिया मतदान तक सीमित हैं।',
    'dashboard.returnToMp': 'एमपी मांग प्राथमिकता इंजन पर लौटें',
    'dashboard.viewportActiveFor': 'दृश्यपोर्ट मोड सक्रिय है:',

    // Admin page
    'admin.title': 'डेटासेट स्वास्थ्य और बैकएंड पुनर्गणना इंजन',
    'admin.pipelineStatus': 'पाइपलाइन स्थिति',
    'admin.onlineSync': '🟢 5 डेटासेट ऑनलाइन और सिंक्रनाइज़',
    'admin.backToDashboard': 'सांसद डैशबोर्ड पर वापस जाएं',
    'admin.systemLogs': 'सिस्टम लॉग और पाइपलाइन आउटपुट',
    'admin.dbscanTitle': 'DBSCAN और मल्टी-फैक्टर पुनर्गणना',
    'admin.verifiedDatasets': 'सत्यापित सरकारी और नगरपालिका डेटासेट',
    'admin.snapshotRollback': 'स्थानिक स्नैपशॉट रोलबैक',
    'admin.uploadBtn': 'पाइपलाइन में नई जीआईएस वेक्टर या जनगणना जियोजेसन फाइल अपलोड करें',
    'admin.triggerBtn': 'अभी पूर्ण बैकएंड पुनर्गणना ट्रिगर करें',

    // Categories
    'cat.all': 'सभी श्रेणियां',
    'cat.road': 'सड़क और पुल',
    'cat.drainage': 'शहरी जल निकासी',
    'cat.healthcare': 'स्वास्थ्य सेवा',
    'cat.water': 'पेयजल',
    'cat.schools': 'स्कूल और शिक्षा',
    'cat.electricity': 'बिजली',
    'cat.all_clusters': 'सभी क्लस्टर',
    'cat.all_complaints': 'सभी शिकायतें',
  },
  od: {
    // Navbar
    'nav.home': 'ହୋମ',
    'nav.explore': 'ම୍ୟାପ ଦେଖନ୍ତୁ',
    'nav.report': 'ଅଭିଯୋଗ ଦାଖଲ',
    'nav.dashboard': 'ଡ୍ୟାଶବୋର୍ଡ',
    'nav.admin': 'ଆଡମିନ',

    // Landing page
    'landing.activeTarget': 'ସକ୍ରିୟ ଲକ୍ଷ୍ୟ',
    'landing.hero1': 'ଅଗ୍ରାଧିକାର ଆଧାରିତ',
    'landing.hero2': 'ନିର୍ବାଚନ ମଣ୍ଡଳୀ ଯୋଜନା।',
    'landing.subtitle': 'People\'s Priorities™ ଆପଣଙ୍କ ସ୍ୱରକୁ ନିଷ୍ପତ୍ତି ନେଉଥିବା ନେତାଙ୍କ ପାଖରେ ପହଞ୍ଚାଏ। ଆମେ ନାଗରିକଙ୍କ ଭଏସ୍ ନୋଟ୍, ଫଟୋ ଏବଂ ରିପୋର୍ଟକୁ ଯାଞ୍ଚ ହୋଇଥିବା ଅଗ୍ରାଧିକାରରେ ପରିଣତ କରୁ।',
    'landing.cta.explore': 'ଲାଇଭ ମ୍ୟାପ ଆରମ୍ଭ କରନ୍ତୁ',
    'landing.cta.report': 'ଅଭିଯୋଗ ଦାଖଲ',
    'landing.howitworks': 'People\'s Priorities™ କିଭଳି କାମ କରେ',
    'landing.howitworks.desc': 'ସାଧାରଣ ନାଗରିକଙ୍କୁ ସିଧାସଳଖ ନିଷ୍ପତ୍ତି ଗ୍ରହଣକାରୀଙ୍କ ସହିତ ଯୋଡୁଥିବା ଏକ ସରଳ ଏବଂ ସ୍ୱଚ୍ଛ ମାଧ୍ୟମ। ଆପଣ ନିଜ ଭାଷାରେ ସ୍ଥାନୀୟ ସମସ୍ୟା ଜଣାନ୍ତୁ—ଆମ ସିଷ୍ଟମ ତାହାକୁ ଯାଞ୍ଚ କରେ ଏବଂ ଜରୁରୀ ଆବଶ୍ୟକତା ଅନୁଯାୟୀ ସଜାଏ।',
    'landing.step1.title': '୧. ସହଜ ନାଗରିକ ରିପୋର୍ଟ',
    'landing.step1.desc': 'ନିଜ ଫୋନରେ ଓଡ଼ିଆ, ହିନ୍ଦୀ, ତେଲୁଗୁ କିମ୍ବା ଇଂରାଜୀରେ ସ୍ୱାଭାବିକ ଭାବରେ କୁହନ୍ତୁ, ଭଙ୍ଗା ରାସ୍ତା କିମ୍ବା ପାଣି ପାଇପର ଫଟୋ ନିଅନ୍ତୁ କିମ୍ବା ଲେଖନ୍ତୁ। ଆମର ସ୍ମାର୍ଟ ସିଷ୍ଟମ ଆପଣଙ୍କ ରିପୋର୍ଟକୁ ତୁରନ୍ତ ଯାଞ୍ଚ କରେ।',
    'landing.step1.badge': 'ଭଏସ୍ ଏବଂ ଫଟୋ ଯାଞ୍ଚ',
    'landing.step2.title': '୨. ସ୍ମାର୍ଟ ଗ୍ରୁପିଂ ଓ ରାଙ୍କିଙ୍ଗ',
    'landing.step2.desc': 'ଯେତେବେଳେ ଅନେକ ପଡ଼ୋଶୀ ଏକା ସମସ୍ୟା ବିଷୟରେ ଜଣାନ୍ତି, ଆମେ ସ୍ୱୟଂଚାଳିତ ଭାବରେ ସେହି ସମସ୍ତ ରିପୋର୍ଟକୁ ଏକ ମୁଖ୍ୟ ହଟସ୍ପଟରେ ଯୋଡୁ ଏବଂ ପ୍ରଭାବିତ ଜନସଂଖ୍ୟା ଆଧାରରେ ପ୍ରାଥମିକତା ସ୍ଥିର କରୁ।',
    'landing.step2.badge': 'ସ୍ୱଚ୍ଛ ଓ ନିରପେକ୍ଷ ପ୍ରାଥମିକତା',
    'landing.step3.title': '୩. ନେତା ଓ ସାଂସଦଙ୍କ ପାଇଁ କାର୍ଯ୍ୟ',
    'landing.step3.desc': 'ନେତା ଏବଂ ସାଂସଦମାନେ ସବୁଠାରୁ ଜରୁରୀ କାର୍ଯ୍ୟର ଏକ ସ୍ପଷ୍ଟ ତାଲିକା ପାଆନ୍ତି—ଯେଉଁଥିରେ ପ୍ରମାଣିତ ଫଟୋ, ନାଗରିକଙ୍କ ଭଏସ୍ ନୋଟ୍ ଏବଂ ଅନୁମାନିକ ବଜେଟ୍ ଥାଏ ଯାହାଦ୍ୱାରା ସଠିକ୍ ସ୍ଥାନରେ ପାଣ୍ଠି ବିନିଯୋଗ ହୋଇପାରିବ।',
    'landing.step3.badge': 'ସିଧାସଳଖ ଜନହିତ ପ୍ରଭାବ',
    'landing.footer.title': 'ଅନୁସନ୍ଧାନ ପାଇଁ ପ୍ରସ୍ତୁତ',
    'landing.footer.desc': '୬୫% କାର୍ଟୋଗ୍ରାଫିକ୍ ଭ୍ୟୁପୋର୍ଟ, ଗଭୀର ପ୍ରମାଣ ଟ୍ୟାବ୍ ଏବଂ ପ୍ରକୃତ ସମୟର ନାଗରିକ ଗୋଇନ୍ଦา ତଥ୍ୟ ଅନୁଭବ କରନ୍ତୁ।',
    'landing.footer.btn1': 'ମ୍ୟାପ ଭ୍ୟୁପୋର୍ଟ ଖୋଲନ୍ତୁ →',
    'landing.footer.btn2': 'ସାଂସଦ ନିଷ୍ପତ୍ତି ମ୍ୟାଟ୍ରିକ୍ସ ଖୋଲନ୍ତୁ',
    'landing.heroRadar': 'ହିରୋ ରାଡାର',
    'landing.clusters': 'କ୍ଲଷ୍ଟର',
    'landing.pinsActive': 'ସକ୍ରିୟ ପିନ',
    'landing.score': 'ସ୍କୋର:',
    'landing.reports': 'ରିପୋର୍ଟ',
    'landing.individualPin': '🟣 ବ୍ୟକ୍ତିଗତ ପିନ୍',
    'landing.monitoredDemand': 'ନିରୀକ୍ଷିତ ଦାବି',
    'landing.noClusters': 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ସକ୍ରିୟ କ୍ଲଷ୍ଟର ନାହିଁ',
    'landing.noClustersDesc': 'ପ୍ରକୃତ ସମୟର GIS ସ୍ଥାନୀୟ କାନଭାସ ଲାଇଭ ଅଛି। DBSCAN କ୍ଲଷ୍ଟରିଂ ଆରମ୍ଭ କରିବାକୁ ଏକ ଯାଞ୍ଚ ହୋଇଥିବା ନାଗରିକ ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ!',
    'landing.deepAnalysis': 'ଗଭୀର ବିଶ୍ଳେଷଣ →',

    // Report page
    'report.title': 'ଏଠାରେ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ',
    'report.canvas': 'ସକ୍ରିୟ କାନଭାସ',
    'report.viewmap': 'ଲାଇଭ ମ୍ୟାପ ଦେଖନ୍ତୁ',
    'report.viewmap.mobile': 'ମ୍ୟାପ ଦେଖନ୍ତୁ',
    'report.gps': 'GPS ଲକ',
    'report.gps.verified': '✓ ପ୍ରମାଣିତ',
    'report.gps.acquiring': 'ଅକ୍ତିଆର କରାଯାଉଛି…',
    'report.gps.denied': 'ସ୍ଥାନ ଅନୁମତି ଅସ୍ୱୀକାର',
    'report.gps.retry': 'ପୁନର୍ବାର ଚେଷ୍ଟା',
    'report.gps.manual': 'ମାନୁଆଲ ପ୍ରବେଶ',
    'report.gps.block': 'ବ୍ଲକ',
    'report.gps.dist': 'ଜିଲ୍ଲା',
    'report.gps.relock': 'GPS ପୁଣି ଲକ କରନ୍ତು',
    'report.category': 'ସମସ୍ୟା ବିଭାଗ ବାଛନ୍ତୁ',
    'report.method': 'ରିପୋର୍ଟ ପ୍ରଣାଳୀ ବାଛନ୍ତୁ',
    'report.method.desc': 'ଭଏସ ମେମୋ, ଫଟୋ ଏବଂ ଟେକ୍ସଟ ସମର୍ଥନ କରେ',
    'report.tab.text': 'ଅଭିଯୋଗ ଲିଖନ୍ତୁ',
    'report.tab.photo': 'ଫଟୋ ପ୍ରମାଣ',
    'report.tab.voice': 'ଭଏସ ରିପୋର୍ଟ',
    'report.voice.lang': 'ଭାଷା:',
    'report.voice.rec': 'ରେକର୍ଡିଂ ଚାଲିଛି… ସ୍ପଷ୍ଟ କୁହନ୍ତୁ',
    'report.voice.recorded': 'ଭଏସ ରିପୋର୍ଟ ରେକର୍ଡ ହେଲା ✓',
    'report.voice.click': 'ରେକର୍ଡ ପାଇଁ ମାଇକ ଦବାନ୍ତୁ',
    'report.voice.stop': 'ବନ୍ଦ ଏବଂ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ',
    'report.voice.play': 'ପ୍ଲେ',
    'report.voice.playing': 'ପ୍ଲେ ହେଉଛି…',
    'report.voice.speak': 'ଜୋରରେ ଏବଂ ସ୍ପଷ୍ଟ ଭାବରେ କୁହନ୍ତୁ',
    'report.photo.click': 'କ୍ୟାମେରା ବ୍ୟବହାର କରି ସମସ୍ୟାର ଫଟୋ ଉଠାନ୍ତୁ',
    'report.photo.or': 'କିମ୍ବା ଫଟୋ ଅପଲୋଡ଼ କରନ୍ତୁ (JPG, PNG, WEBP)',
    'report.photo.btn': '📷 କ୍ୟାମେରା ଖୋଲନ୍ତୁ / ଫାଇଲ ବାଛନ୍ତୁ',
    'report.photo.retake': 'ପୁନର୍ବାର ଫଟୋ ଉଠାନ୍ତୁ',
    'report.text.label': 'ବିସ୍ତୃତ ବିବରଣୀ',
    'report.text.placeholder': 'ଆପଣଙ୍କ ସମସ୍ୟା ଏଠାରେ ଲିଖନ୍ତୁ…',
    'report.submit.text': '📝 ଅଭିଯୋଗ ଦାଖଲ କରି ଲାଇଭ ମ୍ୟାପରେ ପ୍ରକାଶ କରନ୍ତୁ',
    'report.submit.photo': '📷 ଫଟୋ ପ୍ରମାଣ ଦାଖଲ କରି ଲାଇଭ ମ୍ୟାପରେ ପ୍ରକାଶ କରନ୍ତୁ',
    'report.submit.voice': '🎤 ଭଏସ ରିପୋର୍ଟ ଦାଖଲ କରି ଲାଇଭ ମ୍ୟାପରେ ପ୍ରକାଶ କରନ୍ତୁ',
    'report.submit.loading': 'ଅଡ଼ିଟ ଓ ପ୍ରକାଶ ଚାଲୁ ଅଛି…',

    // Explore page
    'explore.title': 'ଲାଇଭ୍ ଅଭିଯୋଗ ଏବଂ ଏଆଇ କ୍ଲଷ୍ଟର ଅଗ୍ରାଧିକାର ମାନଚିତ୍ର',
    'explore.switchReport': 'ଅଭିଯୋଗ ଦାଖଲ',
    'explore.all': 'ସମସ୍ତ ବିଭାଗ',
    'explore.searchPlaceholder': 'ସ୍ଥାନ କିମ୍ବା ବିବରଣୀ ଖୋଜନ୍ତୁ...',
    'explore.filterTitle': 'ବିଭାଗ ଅନୁଯାୟୀ ଫିଲ୍ଟର କରନ୍ତୁ',
    'explore.canvas': 'ସକ୍ରିୟ କାନଭାସ',
    'explore.spatialLedger': 'ସ୍ପାସିଆଲ ଡିମାଣ୍ଡ ଲେଜର',
    'explore.synced': 'ଡ୍ୟାସବୋର୍ଡ ସହିତ ସିଙ୍କ୍ରୋନାଇଜ୍ଡ • 100% ପ୍ରାମାଣିକ ତଥ୍ୟ',
    'explore.clusters': 'କ୍ଲଷ୍ଟର',
    'explore.complaints': 'ଅଭିଯୋଗ',
    'explore.searchPlaceholderClusters': 'କ୍ଲଷ୍ଟର, ବ୍ଲକ, ବିଭାଗ ଖୋଜନ୍ତୁ...',
    'explore.searchPlaceholderReports': 'ଅଭିଯୋଗ ପାଠ୍ୟ, ଭଏସ ଉଦ୍ଧୃତି, ସମସ୍ୟା ଖୋଜନ୍ତୁ...',
    'explore.layer.infra': 'ସରକାରୀ ଭիତ୍ତିଭୂମି',
    'explore.layer.citizen': 'ନାଗରିକ ଇନପୁଟ୍',
    'explore.layer.demographics': 'ଜନସଂଖ୍ୟା',
    'explore.layer.streets': '🗺️ ରାସ୍ତା',
    'explore.layer.satellite': '🛰️ ସାଟେଲାଇଟ୍',
    'explore.tab1': '1. ଏଆଇ ସମୀକ୍ଷା',
    'explore.tab2': '2. 8-ଫ୍ୟାକ୍ଟର ଫର୍ମୁଲା',
    'explore.tab3': '3. ନାଗରିକ ସ୍ୱର',
    'explore.tab4': '4. ଜନଗଣନା ଓ ଜନସଂଖ୍ୟା',
    'explore.tab5': '5. ଜାଲିଆତି ପ୍ରତିରୋଧ',
    'explore.tab6': '6. ସିମୁଲେଟର',
    'explore.tab7': '7. ଅଡିଟ୍ ପୂର୍ବରୁ/ପରେ',
    'explore.drawer.confidence': 'ଉଚ୍ଚ-ବିଶ୍ୱାସ କ୍ଲଷ୍ଟର ଯାଞ୍ଚ ହୋଇଛି',
    'explore.drawer.recAction': 'ସୁପାରିଶ କରାଯାଇଥିବା କାର୍ଯ୍ୟ',
    'explore.drawer.mandate': 'ଫାଷ୍ଟ-ଟ୍ରାକ୍ ମାଣ୍ଡେଟ୍ ଜାରି କରନ୍ତୁ',
    'explore.drawer.aiHeadline': 'ଏଆଇ କାର୍ଯ୍ୟନିର୍ବାହୀ ହେଡଲାଇନ୍',
    'explore.drawer.reasoning': 'ଭୂ-ସ୍ଥାନିକ ଏବଂ ନାଗରିକ ଯୁକ୍ତି',
    'explore.drawer.verifiedReports': 'ଯାଞ୍ଚ ହୋଇଥିବା ନାଗରିକ ରିପୋର୍ଟ',
    'explore.drawer.impactedCitizens': 'ପ୍ରଭାବିତ ନାଗରିକ',
    'explore.drawer.censusSync': 'ଜନଗଣନା ୨୦୧୧/୨୦୨୬ ସିଙ୍କ୍ରୋନାଇଜ୍',
    'explore.drawer.severityRating': 'ଭିତ୍ତିଭୂମି ଗମ୍ଭୀରତା ମାନ୍ୟତା',

    // Dashboard page
    'dashboard.title': 'ଲାଇଭ୍ ଅଗ୍ରାଧିକାର ଡ୍ୟାସବୋର୍ଡ',
    'dashboard.switchmap': 'ଜିଆଇଏସ୍ ମ୍ୟାପ୍ କୁ ଯାଆନ୍ତୁ',
    'dashboard.role.title': 'ସକ୍ରିୟ ଭିଉପୋର୍ଟ ଲେନ୍ସ (ଭୂମିକା-ଆଧାରିତ ପ୍ରବେଶ ନିୟନ୍ତ୍ରଣ):',
    'dashboard.role.mp': 'ସାଂସଦ (ସଂସଦ ସଭ୍ୟ)',
    'dashboard.role.collector': 'ଜିଲ୍ଲାପାଳ / ବିଧାୟକ',
    'dashboard.role.panchayat': 'ପଞ୍ଚାୟତ ସମ୍ପାଦକ',
    'dashboard.weights.title': '8-ଫ୍ୟାକ୍ଟର ଭାର କାଲିବ୍ରେସନ୍',
    'dashboard.weights.reset': 'ରିସେଟ୍',
    'dashboard.weights.desc': 'ନାଗରିକ ଚାହିଦା ବନାମ ଭିତ୍ତିଭୂମି ଅଭାବ କିପରି ର଼୍ୟାଙ୍କ କ୍ରମକୁ ପରିବର୍ତ୍ତନ କରେ ଦେଖିବାକୁ ଫର୍ମୁଲା ଗୁଣକକୁ ଆଡଜଷ୍ଟ କରନ୍ତୁ।',
    'dashboard.weights.demand': 'ନାଗରିକ ଚାହିଦା ବେଗ ଭାର (D)',
    'dashboard.weights.demographic': 'ଜନସଂଖ୍ୟାଗତ ଆବଶ୍ୟକତା ଭାର (P)',
    'dashboard.weights.infra': 'ଭିତ୍ତିଭୂମି ଅଭାବ ଭାର (U)',
    'dashboard.weights.urgency': 'ଜରୁਰୀକାଳୀନ ଏବଂ ସୁରକ୍ଷା ଭାର (G)',
    'dashboard.roleDesc': 'ଏହି ଭିଉରେ ସମସ୍ତ କାର୍ଯ୍ୟ କେବଳ ପଢିବା ପାଇଁ କିମ୍ବା କ୍ଷେତ୍ର ଯାଞ୍ଚ ଏବଂ ନାଗରିକ ମତାମତ ଭୋଟ୍ ମଧ୍ୟରେ ସୀମିତ।',
    'dashboard.returnToMp': 'ସାଂସଦ ଚାହିଦା ଅଗ୍ରାଧିକାର ଇଞ୍ଜିନକୁ ଫେରନ୍ତୁ',
    'dashboard.viewportActiveFor': 'ଭିଉପୋର୍ଟ ମୋଡ୍ ସକ୍ରିୟ ଅଛି:',

    // Admin page
    'admin.title': 'ଡାଟାସେଟ୍ ସ୍ୱାସ୍ଥ୍ୟ ଏବଂ ବ୍ୟାକଏଣ୍ଡ୍ ପୁନର୍ଗଣନା ଇଞ୍ଜିନ୍',
    'admin.pipelineStatus': 'ପାଇପଲାଇନ ସ୍ଥିତି',
    'admin.onlineSync': '🟢 5 ଡାଟାସେଟ୍ ଅନଲାଇନ୍ ଏବଂ ସିଙ୍କ୍ରୋନାଇଜ୍',
    'admin.backToDashboard': 'ସାଂସଦ ଡ୍ୟାସବୋର୍ଡକୁ ଫେରନ୍ତୁ',
    'admin.systemLogs': 'ସିଷ୍ଟମ ଲଗ୍ ଏବଂ ପାଇପଲାଇନ ଆଉଟପୁଟ',
    'admin.dbscanTitle': 'DBSCAN ଏବଂ ମଲ୍ଟି-ଫ୍ୟାକ୍ଟର ପୁନର୍ଗଣନା',
    'admin.verifiedDatasets': 'ଯାଞ୍ଚ ହୋଇଥିବା ସରକାରୀ ଏବଂ ପୌରପାଳିକା ଡାଟାସେଟ୍',
    'admin.snapshotRollback': 'ସ୍ପାସିଆଲ୍ ସ୍ନାପସଟ୍ ରୋଲବ୍ୟାକ୍',
    'admin.uploadBtn': 'ପାଇପଲାଇନକୁ ନୂତନ GIS ଭେକ୍ଟର କିମ୍ବା ଜନଗଣନା GeoJSON ଫାଇଲ୍ ଅପଲୋଡ୍ କରନ୍ତୁ',
    'admin.triggerBtn': 'ଏବେ ସମ୍ପୂର୍ଣ୍ଣ ବ୍ୟାକଏଣ୍ଡ ପୁନର୍ଗଣନା ଆରମ୍ଭ କରନ୍ତୁ',

    // Categories
    'cat.all': 'ସମସ୍ତ ବିଭାଗ',
    'cat.road': 'ରାସ୍ତା ଓ ସେତୁ',
    'cat.drainage': 'ଜଳ ନିଷ୍କାସନ',
    'cat.healthcare': 'ସ୍ୱାସ୍ଥ୍ୟସେବା',
    'cat.water': 'ପାନୀୟ ଜଳ',
    'cat.schools': 'ବିଦ୍ୟାଳୟ ଓ ଶିକ୍ଷା',
    'cat.electricity': '비디우트',
    'cat.all_clusters': 'ସମସ୍ତ କ୍ଲଷ୍ଟର',
    'cat.all_complaints': 'ସମସ୍ତ ଅଭିଯୋଗ',
  },
  te: {
    // Navbar
    'nav.home': 'హోమ్',
    'nav.explore': 'మ్యాప్ చూడండి',
    'nav.report': 'ఫిర్యాదు నమోదు',
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.admin': 'అడ్మిన్',

    // Landing page
    'landing.activeTarget': 'క్రియాశీల లక్ష్యం',
    'landing.hero1': 'ప్రాధాన్యత ఆధారిత',
    'landing.hero2': 'నియోజకవర్గ ప్రణాళిక.',
    'landing.subtitle': 'People\'s Priorities™ మీ గొంతుకను నాయకుల వద్దకు చేరుస్తుంది. పౌరుల వాయిస్ నోట్స్, ఫోటోలు మరియు నివేదికలను ధృవీకరించిన ప్రాధాన్యతలుగా మార్చి, ప్రజా సమస్యలను వేగంగా పరిష్కరించేలా చేస్తుంది.',
    'landing.cta.explore': 'లైవ్ మ్యాప్ ప్రారంభించండి',
    'landing.cta.report': 'ఫిర్యాదు నమోదు చేయండి',
    'landing.howitworks': 'People\'s Priorities™ ఎలా పనిచేస్తుంది',
    'landing.howitworks.desc': 'సాధారణ పౌరులను నేరుగా నిర్ణయాధికారులతో కలిపే సులభమైన మరియు పారదర్శక వేదిక. మీరు మీ భాషలో స్థానిక సమస్యలను తెలియజేస్తే—మా సిస్టమ్ వాటిని సరిచూసి, ప్రాధాన్యత ప్రకారం వరుసక్రమంలో ఉంచుతుంది.',
    'landing.step1.title': '1. సులభమైన పౌర నివేదన',
    'landing.step1.desc': 'మీ ఫోన్‌లో హిందీ, ఒడియా, తెలుగు లేదా ఇంగ్లీషులో సహజంగా మాట్లాడండి, విరిగిన రోడ్డు లేదా నీటి పైపు ఫోటో తీయండి లేదా చిన్న టెక్స్ట్ రాయండి. మా స్మార్ట్ సిస్టమ్ మీ నివేదికను వెంటనే సరిచూస్తుంది.',
    'landing.step1.badge': 'వాయిస్ & ఫోటో ధృవీకరణ',
    'landing.step2.title': '2. స్మార్ట్ గ్రూపింగ్ & ర్యాంకింగ్',
    'landing.step2.desc': 'ఒకే సమస్య గురించి పలువురు ఇరుగుపొరుగు వారు నివేదించినప్పుడు, మేము వాటన్నింటినీ ఒక ప్రధాన హాట్‌స్పాట్‌గా చేర్చి, ప్రభావిత జనాభా మరియు అవసరాల ఆధారంగా ప్రాధాన్యతను నిర్ణయిస్తాము.',
    'landing.step2.badge': 'నిష్పాక్షికమైన & పారదర్శక ర్యాంకింగ్',
    'landing.step3.title': '3. నాయకులు & ఎంపీల కోసం చర్య',
    'landing.step3.desc': 'ప్రజాప్రతినిధులు మరియు ఎంపీలకు అత్యంత అవసరమైన పనుల స్పష్టమైన జాబితా లభిస్తుంది—ఇందులో ధృవీకరించిన ఫోటోలు, పౌరుల వాయిస్ నోట్స్ మరియు అంచనా బడ్జెట్ ఉంటాయి, తద్వారా నిధులు సరైన చోట వినియోగమవుతాయి.',
    'landing.step3.badge': 'ప్రత్యక్ష ప్రజా ప్రయోజనం',
    'landing.footer.title': 'అన్వేషించడానికి సిద్ధంగా ఉంది',
    'landing.footer.desc': '65% కార్టోగ్రాఫిక్ వ్యూపోర్ట్, లోతైన సాక్ష్యం ట్యాబ్‌లు మరియు నిజ-సమయ పౌర మేధస్సును అనుభవించండి.',
    'landing.footer.btn1': 'మ్యాప్ వ్యూపోర్ట్ తెరవండి →',
    'landing.footer.btn2': 'ఎంపీ నిర్ణయ మాతృకను తెరవండి',
    'landing.heroRadar': 'హీరో రాడార్',
    'landing.clusters': 'క్లస్టర్లు',
    'landing.pinsActive': 'సక్రియ పిన్లు',
    'landing.score': 'స్కోర్:',
    'landing.reports': 'నివేదికలు',
    'landing.individualPin': '🟣 వ్యక్తిగత పిన్',
    'landing.monitoredDemand': 'పర్యవేక్షించబడిన డిమాండ్',
    'landing.noClusters': 'ఇంకా ఎటువంటి సక్రియ క్లస్టర్లు లేవు',
    'landing.noClustersDesc': 'నిజ-సమయ GIS ప్రాదేశిక కాన్వాస్ అందుబాటులో ఉంది. DBSCAN క్లస్టరింగ్ను ప్రారంభించడానికి ధృవీకరించబడిన పౌరుడి నివేదికను సమర్పించండి!',
    'landing.deepAnalysis': 'లోతైన విశ్లేషణ →',

    // Report page
    'report.title': 'ఇక్కడ ఫిర్యాదు నమోదు చేయండి',
    'report.canvas': 'క్రియాశీల కాన్వాస్',
    'report.viewmap': 'లైవ్ మ్యాప్‌ను వీక్షించండి',
    'report.viewmap.mobile': 'మ్యాప్ చూడండి',
    'report.gps': 'GPS లాక్',
    'report.gps.verified': '✓ ధృవీకరించబడింది',
    'report.gps.acquiring': 'గుర్తిస్తోంది…',
    'report.gps.denied': 'స్థాన అనుమతి నిరాకరించబడింది',
    'report.gps.retry': 'మళ్లీ ప్రయత్నించండి',
    'report.gps.manual': 'మాన్యువల్ ఎంట్రీ',
    'report.gps.block': 'బ్లాక్',
    'report.gps.dist': 'జిల్లా',
    'report.gps.relock': 'GPS కోఆర్డినేట్లను మళ్ళీ లాక్ చేయండి',
    'report.category': 'సమస్య వర్గాన్ని ఎంచుకోండి',
    'report.method': 'నివేదిక పద్ధతిని ఎంచుకోండి',
    'report.method.desc': 'వాయిస్ మెమోలు, స్మార్ట్‌ఫోన్ ఫోటోలు మరియు టెక్స్ట్‌కు మద్దతు ఇస్తుంది',
    'report.tab.text': 'ఫిర్యాదు రాయండి',
    'report.tab.photo': 'ఫోటో రుజువు',
    'report.tab.voice': 'వాయిస్ నివేదిక',
    'report.voice.lang': 'భాష:',
    'report.voice.rec': 'రికార్డింగ్ అవుతోంది… స్పష్టంగా మాట్లాడండి',
    'report.voice.recorded': 'వాయిస్ నోట్ రికార్డ్ చేయబడింది ✓',
    'report.voice.click': 'రికార్డ్ చేయడానికి మైక్ క్లిక్ చేయండి',
    'report.voice.stop': 'ఆపి, అనువదించండి',
    'report.voice.play': 'ప్లే',
    'report.voice.playing': 'ప్లే అవుతోంది…',
    'report.voice.speak': 'గట్టిగా మరియు స్పష్టంగా మాట్లాడండి',
    'report.photo.click': 'కెమెరాతో సమస్య ఫోటో తీయండి',
    'report.photo.or': 'లేదా ఉన్న ఫోటోను అప్‌లోడ్ చేయండి (JPG, PNG, WEBP)',
    'report.photo.btn': '📷 కెమెరా తెరవండి / ఫైల్ ఎంచుకోండి',
    'report.photo.retake': 'మళ్లీ ఫోటో తీయండి',
    'report.text.label': 'వివరణాత్మక వివరణ',
    'report.text.placeholder': 'మీ సమస్యను ఇక్కడ రాయండి…',
    'report.submit.text': '📝 ఫిర్యాదు సమర్పించి లైవ్ మ్యాప్‌లో ప్రచురించండి',
    'report.submit.photo': '📷 ఫోటో రుజువు సమర్పించి లైవ్ మ్యాప్‌లో ప్రచురించండి',
    'report.submit.voice': '🎤 వాయిస్ నివేదిక సమర్పించి లైవ్ మ్యాప్‌లో ప్రచురించండి',
    'report.submit.loading': 'ఆడిటింగ్ మరియు ప్రచురణ జరుగుతోంది…',

    // Explore page
    'explore.title': 'లైవ్ ఫిర్యాదు & AI క్లస్టర్ ప్రాధాన్యత మ్యాప్',
    'explore.switchReport': 'ఫిర్యాదు నమోదు',
    'explore.all': 'అన్ని వర్గాలు',
    'explore.searchPlaceholder': 'స్థలాలు లేదా వివరణలను శోధించండి...',
    'explore.filterTitle': 'వర్గం ప్రకారం వడపోత',
    'explore.canvas': 'క్రియాశీల కాన్వాస్',
    'explore.spatialLedger': 'ప్రాంతీయ డిమాండ్ లెడ్జర్',
    'explore.synced': 'డాష్‌బోర్డ్‌తో సమకాలీకరించబడింది • 100% ప్రామాణిక డేటా',
    'explore.clusters': 'క్లస్టర్లు',
    'explore.complaints': 'ఫిర్యాదులు',
    'explore.searchPlaceholderClusters': 'క్లస్టర్, బ్లాక్, వర్గం శోధించండి...',
    'explore.searchPlaceholderReports': 'ఫిర్యాదు వచనం, వాయిస్ ట్రాన్స్‌క్రిప్ట్, సమస్య శోధించండి...',
    'explore.layer.infra': 'ప్రజా మౌలిక సదుపాయాలు',
    'explore.layer.citizen': 'పౌరుల ఇన్‌పుట్',
    'explore.layer.demographics': 'జనాభా వివరాలు',
    'explore.layer.streets': '🗺️ వీధులు',
    'explore.layer.satellite': '🛰️ శాటిలైట్',
    'explore.tab1': '1. AI అవలోకనం',
    'explore.tab2': '2. 8-ఫ్యాక్టర్ ఫార్ములా',
    'explore.tab3': '3. పౌరుల గళం',
    'explore.tab4': '4. జనాభా మరియు గణాంకాలు',
    'explore.tab5': '5. మోస నివారణ రక్షణ',
    'explore.tab6': '6. సిమ్యులేటర్',
    'explore.tab7': '7. ఆడిట్ ముందు/తర్వాత',
    'explore.drawer.confidence': 'అధిక-విశ్వాస క్లస్టర్ ధృవీకరించబడింది',
    'explore.drawer.recAction': 'సిఫార్సు చేయబడిన చర్య',
    'explore.drawer.mandate': 'ఫాస్ట్-ట్రాక్ ఆదేశాన్ని జారీ చేయండి',
    'explore.drawer.aiHeadline': 'AI ఎగ్జిక్యూటివ్ హెడ్‌లైన్',
    'explore.drawer.reasoning': 'భూ-ప్రాంతీయ & పౌరుల హేతుబద్ధత',
    'explore.drawer.verifiedReports': 'ధృవీకరించబడిన పౌరుల నివేదికలు',
    'explore.drawer.impactedCitizens': 'ప్రభావిత పౌరులు',
    'explore.drawer.censusSync': 'జనాభా గణన 2021/2026 సమకాలీకరణ',
    'explore.drawer.severityRating': 'మౌలిక సదుపాయాల తీవ్రత రేటింగ్',

    // Dashboard page
    'dashboard.title': 'లైవ్ ప్రాధాన్యత డాష్‌బోర్డ్',
    'dashboard.switchmap': 'జిఐఎస్ మ్యాప్‌కు వెళ్లండి',
    'dashboard.role.title': 'క్రియాశీల వీక్షణ లెన్స్ (పాత్ర-ఆధారిత ప్రాప్యత నియంత్రణ):',
    'dashboard.role.mp': 'ఎంపీ (పార్లమెంటు సభ్యుడు)',
    'dashboard.role.collector': 'జిల్లా కలెక్టర్ / ఎమ్మెల్యే',
    'dashboard.role.panchayat': 'పంచాయితీ కార్యదర్శి',
    'dashboard.weights.title': '8-ఫ్యాక్టర్ బరువు క్రమాంకనం',
    'dashboard.weights.reset': 'రీసెట్',
    'dashboard.weights.desc': 'పౌరుల డిమాండ్ పరిమాణం వర్సెస్ మౌలిక సదుపాయాల అంతరాలను చూడటానికి ఫార్ములా గుణకాలను సర్దుబాటు చేయండి.',
    'dashboard.weights.demand': 'పౌరుల డిమాండ్ వేగ బరువు (D)',
    'dashboard.weights.demographic': 'జనాభా అవసరాల బరువు (P)',
    'dashboard.weights.infra': 'మౌలిక సదుపాయాల లోటు బరువు (U)',
    'dashboard.weights.urgency': 'అత్యవసరం & భద్రత బరువు (G)',
    'dashboard.roleDesc': 'ఈ వీక్షణలో అన్ని చర్యలు కేవలం చదవడానికి మాత్రమే లేదా ఫీల్డ్ ధృవీకరణ చెక్‌లిస్ట్‌లు మరియు పౌరుల అభిప్రాయ ఓటింగ్‌కు పరిమితం చేయబడ్డాయి.',
    'dashboard.returnToMp': 'ఎంపీ డిమాండ్ ప్రాధాన్యత ఇంజిన్‌కు తిరిగి వెళ్ళు',
    'dashboard.viewportActiveFor': 'వ్యూపోర్ట్ మోడ్ సక్రియంగా ఉంది:',

    // Admin page
    'admin.title': 'డేటాసెట్ ఆరోగ్యం & బ్యాకెండ్ రీకాలిక్యులేషన్ ఇంజన్',
    'admin.pipelineStatus': 'పైప్‌లైన్ స్థితి',
    'admin.onlineSync': '🟢 5 డేటాసెట్‌లు ఆన్‌లైన్ & సమకాలీకరించబడ్డాయి',
    'admin.backToDashboard': 'ఎంపీ డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి',
    'admin.systemLogs': 'సిస్టమ్ లాగ్‌లు & పైప్‌లైన్ అవుట్‌పుట్',
    'admin.dbscanTitle': 'DBSCAN & మల్టీ-ఫ్యాక్టర్ రీకాలిక్యులేషన్',
    'admin.verifiedDatasets': 'ధృవీకరించబడిన ప్రభుత్వ & పురపాలక డేటాసెట్లు',
    'admin.snapshotRollback': 'ప్రాంతీయ స్నాప్‌షాట్ రోల్‌బ్యాక్',
    'admin.uploadBtn': 'పైప్‌లైన్‌కు కొత్త GIS వెక్టర్ లేదా సెన్సస్ GeoJSON ఫైల్‌ను అప్‌లోడ్ చేయండి',
    'admin.triggerBtn': 'ఇప్పుడే పూర్తి బ్యాకెండ్ రీకాలిక్యులేషన్‌ను ప్రారంభించండి',

    // Categories
    'cat.all': 'అన్ని వర్గాలు',
    'cat.road': 'రోడ్లు & వంతెనలు',
    'cat.drainage': 'పట్టణ నీటి పారుదల',
    'cat.healthcare': 'ఆరోగ్య సేవలు',
    'cat.water': 'తాగు నీరు',
    'cat.schools': 'పాఠశాలలు & విద్య',
    'cat.electricity': 'విద్యుత్',
    'cat.all_clusters': 'అన్ని క్లస్టర్లు',
    'cat.all_complaints': 'అన్ని ఫిర్యాదులు',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<AppLanguage>('en');

  const t = (key: string): string => {
    return translations[language][key] ?? translations['en'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
